spring:
  datasource:
    url: jdbc:mysql://43.138.189.131:3306/java2?useUnicode=true&characterEncoding=utf-8
    username: quanquan
    password: wlqyanyalun008++

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
