spring:
  datasource:
    url: jdbc:mysql://43.138.189.131:3306/java2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: quanquan-springboot
    password: wlqyanyalun008++
debug: true

mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: edu.sustech.backend.dto
